# Generated by Django 3.0.6 on 2020-10-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'животное',
                'verbose_name_plural': 'животные',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской')], max_length=128)),
                ('protection_time', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('protected_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Animals_Info.Animal')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Animal_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('predator', 'Хищник'), ('herbivorous', 'Травоядный'), ('omnivorous', 'Всеядный')], max_length=128)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animals_Info.Animal')),
            ],
            options={
                'verbose_name': 'животного с определенным типом питания',
                'verbose_name_plural': 'животные по типу питания',
            },
        ),
        migrations.CreateModel(
            name='Animal_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('place_type', models.CharField(choices=[('cell', 'Клетка'), ('enclosure', 'Вольер'), ('terrarium', 'Террариум')], max_length=128)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name_animal', models.ManyToManyField(to='Animals_Info.Animal')),
            ],
            options={
                'verbose_name': 'животного с определенным местом содержания',
                'verbose_name_plural': 'места содержания животных',
            },
        ),
    ]
