# Generated by Django 3.0.6 on 2020-10-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animals_Info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(default=1, max_length=300, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='temper',
            field=models.CharField(choices=[('wild', 'Буйный'), ('changing', 'Переменчивый'), ('peaceful', 'Спокойный')], default=1, max_length=128, verbose_name='характер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_place',
            name='description',
            field=models.TextField(default=1, max_length=300, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_place',
            name='heat',
            field=models.CharField(choices=[('heatable', 'Отапливаемый'), ('unheated', 'Неотапливаемый')], default=1, max_length=128, verbose_name='отопление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_type',
            name='description',
            field=models.TextField(default=1, max_length=300, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_type',
            name='independence',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default=1, max_length=128, verbose_name='самостоятельное питание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_type',
            name='safe_feeding',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default=1, max_length=128, verbose_name='безопасное кормление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(default=1, max_length=300, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(verbose_name='возраст в годах'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='зарегестрирован'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=128, verbose_name='кличка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nickname',
            field=models.CharField(max_length=128, verbose_name='порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='отредактирован'),
        ),
        migrations.AlterField(
            model_name='animal_place',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='зарегестрирован'),
        ),
        migrations.AlterField(
            model_name='animal_place',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название места содержания'),
        ),
        migrations.AlterField(
            model_name='animal_place',
            name='name_animal',
            field=models.ManyToManyField(to='Animals_Info.Animal', verbose_name='животное'),
        ),
        migrations.AlterField(
            model_name='animal_place',
            name='place_type',
            field=models.CharField(choices=[('cell', 'Клетка'), ('enclosure', 'Вольер'), ('terrarium', 'Террариум')], max_length=128, verbose_name='тип содержания'),
        ),
        migrations.AlterField(
            model_name='animal_place',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='отредактирован'),
        ),
        migrations.AlterField(
            model_name='animal_type',
            name='animal_type',
            field=models.CharField(choices=[('predator', 'Хищник'), ('herbivorous', 'Травоядный'), ('omnivorous', 'Всеядный')], max_length=128, verbose_name='тип питания'),
        ),
        migrations.AlterField(
            model_name='animal_type',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='зарегестрирован'),
        ),
        migrations.AlterField(
            model_name='animal_type',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animals_Info.Animal', verbose_name='животное'),
        ),
        migrations.AlterField(
            model_name='animal_type',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='отредактирован'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='зарегестрирован'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской')], max_length=128, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=128, verbose_name='имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='protected_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Animals_Info.Animal', verbose_name='наблюдаемое животное'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='protection_time',
            field=models.IntegerField(verbose_name='время наблюдения '),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='отредактирован'),
        ),
    ]
