# Generated by Django 3.0.6 on 2020-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals_Info', '0002_auto_20201008_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_place',
            old_name='name_animal',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='animal_place',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='animal_type',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='описание'),
        ),
    ]
