# Generated by Django 3.0.6 on 2020-10-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animals_Info', '0005_auto_20201008_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_place',
            old_name='nickname_3',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='animal_place',
            name='nickname_1',
        ),
        migrations.RemoveField(
            model_name='animal_place',
            name='nickname_2',
        ),
    ]
