# Generated by Django 3.0.6 on 2020-10-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animals_Info', '0008_auto_20201008_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_place',
            name='nickname_1',
        ),
    ]
