# Generated by Django 3.0.6 on 2020-10-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals_Info', '0010_auto_20201008_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='protection_time',
            field=models.IntegerField(verbose_name='время наблюдения (дней)'),
        ),
    ]
