# Generated by Django 3.1.2 on 2020-10-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals_Info', '0011_auto_20201014_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Женский'), ('male', 'Мужской')], max_length=128, null=True, verbose_name='пол'),
        ),
    ]
