# Generated by Django 3.1.2 on 2020-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals_Info', '0012_auto_20201020_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_place',
            name='nickname_1',
        ),
        migrations.RemoveField(
            model_name='animal_place',
            name='nickname_2',
        ),
        migrations.RemoveField(
            model_name='animal_place',
            name='nickname_3',
        ),
        migrations.AddField(
            model_name='animal_place',
            name='nickname_a',
            field=models.ManyToManyField(blank=True, to='Animals_Info.Animal', verbose_name='размещенные животные'),
        ),
    ]
